// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiFIzZUUwFCZEiLnlSDfF5Ko4hXDyAdIU',
    appId: '1:123228196272:web:125e9f15a36c0b75959a75',
    messagingSenderId: '123228196272',
    projectId: 'snapshare-b9b1d',
    authDomain: 'snapshare-b9b1d.firebaseapp.com',
    storageBucket: 'snapshare-b9b1d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Bkb2OD0A7KNL5GCoPnyAhxfHZV5QRPU',
    appId: '1:123228196272:android:39d0e8eedabdcc49959a75',
    messagingSenderId: '123228196272',
    projectId: 'snapshare-b9b1d',
    storageBucket: 'snapshare-b9b1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP-bhrVdvTSsGu__rjgqxW0O3pqcmn4FI',
    appId: '1:123228196272:ios:ce5671386233db0d959a75',
    messagingSenderId: '123228196272',
    projectId: 'snapshare-b9b1d',
    storageBucket: 'snapshare-b9b1d.appspot.com',
    iosBundleId: 'com.example.snapShareOrange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP-bhrVdvTSsGu__rjgqxW0O3pqcmn4FI',
    appId: '1:123228196272:ios:ce5671386233db0d959a75',
    messagingSenderId: '123228196272',
    projectId: 'snapshare-b9b1d',
    storageBucket: 'snapshare-b9b1d.appspot.com',
    iosBundleId: 'com.example.snapShareOrange',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiFIzZUUwFCZEiLnlSDfF5Ko4hXDyAdIU',
    appId: '1:123228196272:web:8a2fa13f2cf7a804959a75',
    messagingSenderId: '123228196272',
    projectId: 'snapshare-b9b1d',
    authDomain: 'snapshare-b9b1d.firebaseapp.com',
    storageBucket: 'snapshare-b9b1d.appspot.com',
  );
}
